config/routes.rb
Rails.application.routes.draw do
  get '/home/about', to: 'books#about'
  root 'books#top'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:top, :create, :index, :show, :edit, :update, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 50 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  def top
  end

  def about
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'successfully created'
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render action: :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new 
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def edit
    if current_user == Book.find(params[:id]).user
      @book = Book.find(params[:id])
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'successfully updated'
    else 
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path, notice: 'successfully deleted'
    else
      render action: :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
  <% if @book.errors.any? %>
    <ul>
    <p>error</p>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>    
<% end %>
<%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p><%= notice %></p>
  

<div class="container">
    <div class="row">
      <div class="col-xs-3">
        <div class="sidebar_content">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %><br>
        <table class="table">
          <tr>
            <th>name</td> <td><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</td> <td><%= @user.introduction %></th>
          </tr>
          
        </table>
          <% if @user.id == current_user.id %>
            <div class="row">
              <%= link_to edit_user_path(@user) do %><button type="button" class="col-xs-12 btn btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span></button><% end %>
            </div>
          <% end %>
        </div>
      

        <div class="sidebar_content">
          <h2>New book</h2>

          <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <ul>
            <p>error</p>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
              <% end %>
  
              <div class="row">
                <h5>Title</h5>
                <%= f.text_field :title, class: "col-xs-12" %>
              </div>
            
              <div class="row">
                <h5>Opinion</h5>
                <%= f.text_area :body, class: "col-xs-12" %>
              </div><br>
  
              <div class="row">
                <%= f.submit 'Create Book', class: " col-xs-12 btn btn-primary btn-block" %>
              </div>
          <% end %>
        </div>
      </div>
    


      <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th colspan="1"></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %><% end %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
    </div>
</div>



  

app/views/books/show.html.erb
<p><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <div class="sidebar_content">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %><br>
      <table class="table">
        <tr>
          <th>name</td> <td><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</td> <td><%= @user.introduction %></th>
        </tr>
        
      </table>
        <% if @user.id == current_user.id %>
          <div class="row">
            <%= link_to edit_user_path(@user) do %><button type="button" class="col-xs-12 btn btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true" ></span></button><% end %>
          </div>
        <% end %>

      </div>

      <div class="sidebar_content">
      <h2>New book</h2>
      <%= form_for(@new_book) do |f| %>
        <% if @new_book.errors.any? %>
        <ul>
        <p>error</p>
          <% @new_book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
          <% end %>

          <div class="row">
            <h5>Title</h5>
            <%= f.text_field :title, class: "col-xs-12" %>
          </div>
        
          <div class="row">
            <h5>Opinion</h5>
            <%= f.text_area :body, class: "col-xs-12" %>
          </div><br>

          <div class="row">
            <%= f.submit 'Create Book', class: " col-xs-12 btn btn-primary btn-block" %>
          </div>
      <% end %>
      </div>
    </div>
  

    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to user_path(@book.user.id) do %><%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %><%= @book.user.name %><% end %></td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
          <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-default btn-success btn-xs" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-default btn-danger btn-xs" %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    
  </div>
</div>

app/views/books/top.html.erb
 
  <p><%= notice %></p>
  


  <div class="container">
    <div class="row">
      <div class="col-xs-12">
    
        <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
      </div>
    </div>
    
    <div class="row">
      <div class="col-xs-12">
        In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
      </div>
    </div>

    <dic class="row">
      <div class="col-xs-12">
        <div class="btn-group-vertical" role="group" style="width: 100%;">
          <button type="button" class="btn btn-default btn-info"><%= link_to "Log in", new_user_session_path %></button>
          <button type="button" class="btn btn-default btn-success"><%= link_to "Sign Up", new_user_registration_path %></button>
        </div>  
      </div>
    </div>
  </div>