config/routes.rb
Rails.application.routes.draw do
  get '/home/about', to: 'books#about'
  root 'books#top'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:top, :create, :index, :show, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <% if user_signed_in? %>

      <header class="navbar navbar-inverse">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <nav class="nav navbar-nav navbar-left">
                <span class="navbar-brand">
                  Bookers
                </span>
              </nav>
              
              <nav>
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to user_path(current_user.id) do %><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home<% end %></li>
                  <li><%= link_to users_path do %><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Users<% end %></li>
                  <li><%= link_to books_path do %><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Books<% end %></li>
                  <li><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>logout<% end %></li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </header>

    <% else %>

      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <span class="navbar-brand">
              Bookers
            </span>
          </div>  
        
          <div class="collapse navbar-collapse" >
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to root_path do %><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home<% end %></li>
              <li><%= link_to home_about_path do %><span class="glyphicon glyphicon-link" aria-hidden="true"></span>About<% end %></li>
              <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>sign up<% end %></li>
              <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>login<% end %></li>
            </ul>
          </div>
        </div>
      </nav>
    

    <% end %>

    <%= yield %>

    <div class="container">
      <div class="footer row">
        <div class="col-xs-9">
        </div>
        <div class="col-xs-3">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>

  </body>
</html>